### ISSUE TITLE
Play button does not work till speed slider fps button is pressed once.

### ISSUE THREAD

**Issue by apiitnomi** [socib/Leaflet.TimeDimension#1]
This is great plugin, I appreciate your efforts.

I am try to get the play button to work but have to first click the fps, speed slider button to get it to work.

**Comment by bielfrontera** [comment]
Hi, thanks for your feedback.

Could you fork [this fiddle](http://jsfiddle.net/bielfrontera/ecu0hx7z/2/) and adapt it to see what's going wrong? 

It might be a problem initializing the buffer. By default, the player waits until the next 5 times are loaded  (according to parameters buffer and minBufferReady). If any of these next times fail to load, it might cause the player to wait forever (I have to check this). 

When you change the speed, the player stops and restart with the new settings. And then, if it has any of the next times ready, it will continue.

**Comment by apiitnomi** [comment]
yes I tried this fork and it works :)

**Comment by bielfrontera** [comment]
Great! I would close the issue, then.

**Comment by apiitnomi** [comment]
ok, also I when I view in chrome on Andriod 4.4 I the timeslider is compressed on to its full length
