### ISSUE TITLE
Play and cache

### ISSUE THREAD

**Issue by darkat** [socib/Leaflet.TimeDimension#10]
Hi,
I found an error when i playing and move the map (or change zoom). 
The plugin save in cache the next X layers that are currently visible, and when i move the map don't load the new tiles until the cache is empty.

![captura2](https://cloud.githubusercontent.com/assets/8228219/10788744/b7766a52-7d79-11e5-8425-32595f4180e1.PNG)

**Comment by bielfrontera** [comment]
Hi, yes, its an issue. 
The plugin should invalidate the cache after panning or zoom events are detected.

**Comment by bielfrontera** [comment]
Fixed in #25
