### ISSUE TITLE
What is the best example to start from when implementing a timeline from multiple TileLayers?

### ISSUE THREAD

**Issue by boriskogan81** [socib/Leaflet.TimeDimension#103]
Hi, guys, 

I've got a RESTful API pushing .png-based TileLayers and associated metadata (datetime, lat/lon, etc.)

I'd like to create a time slider or animation to display them as per the user's inputs.

What is a good starting point?

**Comment by bielfrontera** [comment]
Hi @boriskogan81,
I've just uploaded a new example ([16. Portus wave forecast](http://apps.socib.es/Leaflet.TimeDimension/examples/example16.html)) where TimeDimension creates a new TileLayer for each time modifying the URL (time is part of the URL of the layer).
It can be an starting point.

If you have to call your API to get layer information for each time, you can check [example 12](http://apps.socib.es/Leaflet.TimeDimension/examples/example12.html).

**Comment by boriskogan81** [comment]
That's beautiful, thank you!

Sincerely,

Baruch
