### ISSUE TITLE
Geojson - Remove features past data

### ISSUE THREAD

**Issue by rainitesh** [socib/Leaflet.TimeDimension#104]
I have a geojson with the same point feature duplicated 5 times with different time attribute. I am trying to display changes over time by controlling the circle radius.

It works fine but the only problem is the circles overlay on top of each other reducing the transparency over time. It becomes darker and darker. Is there a way to remove the features at the same location as time moves on and add them again as we move time back?

Attached images below. Any help is appreciated. 
![image](https://cloud.githubusercontent.com/assets/16216239/26570021/79405c60-4551-11e7-9d53-1ee530396f2e.png)

![image](https://cloud.githubusercontent.com/assets/16216239/26570032/8f3b2932-4551-11e7-9845-7be9149af0e7.png)

**Comment by bielfrontera** [comment]
You could remove all past features using the option `duration` (in the TimeDimension.GeoJSON layer).
But if you want to remove only the reapeated features, you would need to extend the GeoJSON class to override the `_update` method. There, you can manage which features are added to the new geojson layer.

**Comment by rainitesh** [comment]
@bielfrontera I was able to manage the features by editing the minTime values. Thanks for the guidance.
