### ISSUE TITLE
NOAA weather example no longer working

### ISSUE THREAD

**Issue by ProteanHub** [socib/Leaflet.TimeDimension#105]
The timeline shows as not available. Did NOAA change something on their end?

**Comment by sonic6567** [comment]
I can confirm that this stopped working.  Any changes?  Any fix?

**Comment by bielfrontera** [comment]
Hi!
There is a problem with the GetCapabilites request. NOAA's server returns a '403 Forbidden' to this request: https://nowcoast.noaa.gov/arcgis/services/nowcoast/radar_meteo_imagery_nexrad_time/MapServer/WMSServer?request=GetCapabilities&service=WMS&version=1.3.0 (when requested from the server)

So I've changed the example, and now it defines the availabletimes without requesting this info from GetCapabilities.

**Comment by ProteanHub** [comment]
Confirmed working again. Thanks for the quick fix!
