### ISSUE TITLE
TimeDimension without using MapServer

### ISSUE THREAD

**Issue by candidobugarin** [socib/Leaflet.TimeDimension#11]
Hello,
I'm try use the TimeDimension to animate and show images of radar in Brasil, but i'm not have a MapServer. It's possible use the TimeDimension to make that?

**Comment by bielfrontera** [comment]
Hi @candidobugarin,
you can use TimeDimension to manage an animation of ImageOverlays.

First of all, try to show just one radar image into a leaflet map using ImageOverlay.

Then, you could adapt the code of the [example 10](http://apps.socib.es/Leaflet.TimeDimension/examples/example10.html), where you will find an implementation of the class `L.TimeDimension.Layer.ImageOverlay`. Note that you will need to pass a function to `getUrlFunction` option to specify how to construct each image url depending on time.

**Comment by candidobugarin** [comment]
Hi,
I use ImageOverlay on the map, this is the page's url:
http://www.alertadecheias.com.br/chuva/bacia.html
But, with your idea, i go animate the imagens.
Thanks

2015-11-10 10:41 GMT-02:00 Biel Frontera <notifications@github.com>:
