### ISSUE TITLE
Does not work with Jquery in noConflict mode

### ISSUE THREAD

**Issue by Ram-one** [socib/Leaflet.TimeDimension#12]
The use of global $ prevents the use of the library with jquery.noConflict().

Maybe you should wrap this in
```
(function($) { 
 //code
})(jQuery );
```
or use ```jQuery ``` variable instead

**Comment by bielfrontera** [comment]
Hi @Ram-one,
thanks for the advise. 

I've modified the grunt configuration file to generate the dist code wrapped as you proposed.

**Comment by Ram-one** [comment]
Thanks.
