### ISSUE TITLE
Time dimension with angular 4 + ngx-leaflet

### ISSUE THREAD

**Issue by matijamatija** [socib/Leaflet.TimeDimension#131]
Has anyone managed to run this with angular 4 (and ngx-leaflet)?

**Comment by reblace** [comment]
See: https://github.com/Asymmetrik/ngx-leaflet/issues/101

**Comment by matijamatija** [comment]
Just to confirm here also. 
This was solved on ngx-leaflet Github issue. 
Thanks again @reblace for help.
