### ISSUE TITLE
Customizing the marker

### ISSUE THREAD

**Issue by karussell** [socib/Leaflet.TimeDimension#14]
How can I change the marker of the 'current position' without overwriting the marker-icon.png :) ?

BTW: I'm speaking of the `addlastPoint: true` option

Somehow one needs to replace [this](https://github.com/socib/Leaflet.TimeDimension/blob/master/src/leaflet.timedimension.layer.geojson.js#L75) with e.g. a custom marker:
```js
var marker = L.marker([lat, lon]);
var icon = L.icon({
    iconUrl: './path-to-im/test.png',            
    iconSize: [24, 24],
    iconAnchor: [10, 10]
});
marker.setIcon(icon);
marker.addTo(vrpMap);
```

**Comment by Ram-one** [comment]
I guess you can use ```pointToLayer``` option on leaflet layer
http://leafletjs.com/reference.html#geojson

**Comment by karussell** [comment]
Nice, I'll try. thanks for the hint!

**Comment by Ram-one** [comment]
See [example 8](https://github.com/socib/Leaflet.TimeDimension/blob/master/examples/js/example8.js#L34)

**Comment by karussell** [comment]
Thanks again, so I guess we can close here :)

**Comment by karussell** [comment]
Maybe this should be easier via a property but maybe this is not so complex ...

**Comment by karussell** [comment]
Hmmh, I do not get it working. The example seems to be too far away from what I need. I tried to modify the example but I'm e.g. unsure where to get the `data` or if I need (and how) this works in the _createLayer method

**Comment by Ram-one** [comment]
I did not check my code, but this should do:

```javascript
//init your data
var map=...:
var icon =...;
var geoJsonData = ...;
//declare a normal GeoJson layer 
var geojsonLayer = L.geoJson(geoJsonData , {
            pointToLayer: (function(feature, latLng) {
                //check if it's the last point added
                if (feature.properties.hasOwnProperty('last')) {
                    return new L.Marker(latLng, {
                        icon: icon
                    });
                }
                //else
                return L.circleMarker(latLng, {
                    fillColor: 'red',
                    fillOpacity: 0.5,
                    stroke: false,
                    radius: 3
                });
            })
        });
// Add time capability to the geojson layer
var geoJsonTimeLayer = L.timeDimension.layer.geoJson(geojsonLayer , {
    addlastPoint: true
});
//add the timed layer to the map
geoJsonTimeLayer .addTo(map);
```

**Comment by karussell** [comment]
Looks simpler then, thanks a lot! But still not working :(

Not sure if my complication due to gpx makes this not working but with this code, it is still showing the default end marker as the 'pointToLayer' is never called:
```js
var gpxLayer = L.geoJson();
gpxLayer.pointToLayer = function (feature, latLng) {
    if (feature.properties.hasOwnProperty('last')) {
        return new L.Marker(latLng, {
            icon: icon
        });
    }
    //else
    return L.circleMarker(latLng, {
        fillColor: 'red',
        fillOpacity: 0.5,
        stroke: false,
        radius: 3
    });
};

gpxLayer = omnivore.gpx(url, null, gpxLayer).on('ready', function () {});
var geoJsonLayer = L.timeDimension.layer.geoJson(gpxLayer, {
    updateTimeDimension: true,
    addlastPoint: true
});

geoJsonLayer.addTo(vrpMap);
```

And the GPX is necessary for the additional time information

**Comment by Ram-one** [comment]
You are not passing it as option.
```javascript
L.geoJson(null, {
    pointToLayer: function() {
        // todo
    }
});
```

**Comment by karussell** [comment]
Sorry, didn't mention it: this was my first try and was also without success...

**Comment by karussell** [comment]
I think the plugin needs an update [here](https://github.com/socib/Leaflet.TimeDimension/blob/master/src/leaflet.timedimension.layer.geojson.js#L65) to take into account the pointToLayer hook

**Comment by karussell** [comment]
Uhm, my fault, sorry - there was some `style` overwriting the options!

Here is the short and working code:
```js
var icon = L.icon({
    iconUrl: 'img/myImage.png',
    iconSize: [24, 24],
    iconAnchor: [10, 10]
});

var gpxLayer = omnivore.gpx(url).on('ready', function () {
});
gpxLayer.options = {
    style: myStyle,
    pointToLayer: function (feature, latLng) {
        if (feature.properties.hasOwnProperty('last')) {
            return new L.Marker(latLng, {
                icon: icon
            });
        }
        //else
        return new L.Marker(latLng, {
            icon: icon2
        });
    }
};

var geoJsonLayer = L.timeDimension.layer.geoJson(gpxLayer, {
    updateTimeDimension: true,
    addlastPoint: true
});


geoJsonLayer.addTo(map);
```

**Comment by bielfrontera** [comment]
Hi!
Exactly, here the trick was to create a layer with the option `pointToLayer`, and call omnivore with this custom layer. Then, it works, because TimeDimension creates new geoJson layers inheriting the same options of the base layer.

I have update example 9, and now it appears a different marker.

I think there is no need to add an option to timedimension, because in other cases you might need to modify other options of the geojson base layer.

But I should modify the documentation, to explain that timedimension adds a special property `last` to geoJson features which can be used to modify the style.

**Comment by karussell** [comment]
Thanks @bielfrontera !
