### ISSUE TITLE
Can the `displayDate` be formatted?

### ISSUE THREAD

**Issue by Craicerjack** [socib/Leaflet.TimeDimension#145]
Im wondering can the `displayDate` be formatted? 
![screenshot from 2018-03-29 17-00-21](https://user-images.githubusercontent.com/4867797/38099527-bd5bdac2-3372-11e8-9781-7151a536f4ef.png)

**Comment by pazrg** [comment]
Hi @Craicerjack;
Sorry to reply this late!
There are several ways to get what you want; here you can find at least 2 examples on our [demos](http://apps.socib.es/Leaflet.TimeDimension/examples/):
[example 11](http://apps.socib.es/Leaflet.TimeDimension/examples/example11.html)
[example 12](http://apps.socib.es/Leaflet.TimeDimension/examples/example12.html)

All of them extend L.Control.TimeDimension i.e as follows:
L.Control.TimeDimensionCustom = L.Control.TimeDimension.extend({
    _getDisplayDateFormat: function(date){
        return date.format("mmmm yyyy");
    }
});

Hope this help! Let us know from you!

**Comment by Craicerjack** [comment]
@pazrg  Thanks. Yeah I figured it out. APologies I should have closed the issue.

**Comment by ErikaHD** [comment]
Hi Craicerjack,
Could you tell me how you solve your issue? I am having the same problem. Thanks
