### ISSUE TITLE
CSS for slider should be selectable

### ISSUE THREAD

**Issue by karussell** [socib/Leaflet.TimeDimension#15]
Currently we have 
`leaflet-control-timecontrol timecontrol-slider` as css class for the time slider and 
`leaflet-control-timecontrol timecontrol-slider timecontrol-speed` for the FPS slider. So one cannot easily select the time slider without selecting also the FPS slider

**Comment by bielfrontera** [comment]
Fixed! Now you have timecontrol-dateslider to select it.

**Comment by karussell** [comment]
Thanks!
