### ISSUE TITLE
Error: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by beefhotpot** [socib/Leaflet.TimeDimension#157]
Hi, I'm trying to create and add a timeDimension layer to the map, using my WMS layer provided by geoserver.
I assume it should be easy but I got the error:
No 'Access-Control-Allow-Origin' header is present on the requested resource.
Anyone can help me on this? 
Cheers

**Comment by VictorVelarde** [comment]
You have to enable CORS in your server, so the plugin can work, requesting some otherwise blocked metadata. Have a look at http://docs.geoserver.org/latest/en/user/production/container.html

**Comment by leandrosramirez** [comment]
hanks Victor, I had the same problem and can solve it with your help.
