### ISSUE TITLE
Setting custom style in Example 12

### ISSUE THREAD

**Issue by ahwKs** [socib/Leaflet.TimeDimension#16]
Hi,
Hope I am here at the correct address, please otherwise delete this issue!

Based on example 12, I tried to load GeoJson data including several polygons and draw them using GeoJson prototype instead of heatmap. (http://apps.socib.es/Leaflet.TimeDimension/examples/example12.html)
Now I want to assign each polygon his own color based on a field in the GeoJson file (properties.color). The default examples I found (defining a style function, setStyle) I did not get working. 
Is there a best practise to assign style attributes to layer in combination with TimeDimension and the step by step loading procedure of example 12?

**Comment by bielfrontera** [comment]
Hi,
you can add the style option on the base GeoJson layer.
TimeDimension creates new GeoJson layers with the same options of the base layer. Therefore, they inherit this style option.

Check [example 15, line 81](https://github.com/socib/Leaflet.TimeDimension/blob/master/examples/js/example15.js#L81)

**Comment by ahwKs** [comment]
Hi,
Adding it to the BaseLayer was the missing piece! Thanks a lot! Now it works!
