### ISSUE TITLE
Not working with Leaflet 1.5.1 (latest version)

### ISSUE THREAD

**Issue by prasanjitdash** [socib/Leaflet.TimeDimension#172]
LL Time Dimension Versin: Leaflet TimeDimension v1.1.0 - 2017-10-13

Issue: I'm using (in localhost) TimeDimension with Leaflet 1.4.0 and don
t have any issue in its simplest implementation. However, when I changed to LL version 1.5.1, the following error appears in the Chrome Console:

`leaflet.js:5 Uncaught TypeError: Cannot read property 'insertBefore' of undefined`
`at i.addTo (leaflet.js:5)`
`at i.addTo (leaflet.timedimension.control.js:192)`
`at i.addControl (leaflet.js:5`

Please shar your thoughts or any insight. Thanks

**Comment by bielfrontera** [comment]
Hi @prasanjitdash,
apologies for the delayed response (I'm back to this project after a temporary leave). 

I've checked the plugin with Leaflet 1.5.1 and I've not found any error. Could you with us more details about your code?

**Comment by prasanjitdash** [comment]
No issues with the delay - it is hard to juggle between so many things we do. I've almost forgotten the details of what I did that time and will re-visit soon to check if the newer solution works well. In the meanwhile, thank you for your time and for getting back to this useful plugin improvement.
