### ISSUE TITLE
Add moment-jalaali to change convert date and time to jalali calendar from 

### ISSUE THREAD

**Issue by rahimramezanian** [socib/Leaflet.TimeDimension#176]
The date time slider is always in Georgian calendar, Would you please use something like
https://github.com/jalaali/moment-jalaali
to also support Jalali calendar.
Thanks.

**Comment by bielfrontera** [comment]
Hi @rahimramezanian,
you can customize how the date is displayed creating a custom `L.Control.TimeDimension` and overwritting the method `_getDisplayDateFormat`. 

Example: 
```javascript
L.Control.TimeDimensionCustom = L.Control.TimeDimension.extend({
    _getDisplayDateFormat: function(date){
        return moment(date, 'jYYYY/jM/jD');
    }
});
var timeDimensionControl = new L.Control.TimeDimensionCustom({});
map.addControl(this.timeDimensionControl);
```
More information at #145

**Comment by rahimramezanian** [comment]
Hi @bielfrontera 
Thanks.
