### ISSUE TITLE
Common features

### ISSUE THREAD

**Issue by fox91** [socib/Leaflet.TimeDimension#18]
Hi,
is a little time that I use this plugin and I write some things that could be useful to many developers:
  - why not use tags git for the versions?
  - why dependencies are written in the [`README.md`](https://github.com/socib/Leaflet.TimeDimension/blob/master/README.md#requisites) and not in [`package.json`](https://github.com/socib/Leaflet.TimeDimension/blob/master/package.json)?

One piece of advice I can give is to make the plugin also available through bower and not only as a package npm.

If you agree I can give you a hand to do some of the things that I have suggested.

**Comment by bielfrontera** [comment]
Hi @fox91,
of course you can help with these things! 

Can you send a PR with the modification of `package.json` and the new `bower.json` file?
Then, I can tag the repository with the current version (0.1.6). 

Feel free to collaborate with other suggestions. Thanks!

**Comment by fox91** [comment]
Hi @bielfrontera,
in the coming days I will provide the changes!
