### ISSUE TITLE
Slider not displayed in v1.1.1

### ISSUE THREAD

**Issue by ChandiniGanesan** [socib/Leaflet.TimeDimension#181]
Hi I created a python visualization using HeatMapWithTime and it was working fine using v1.1.0
However I feel there is a bug in v1.1.1 that does not show the plots or slider bar.

Please revert 1.1.0 to master or fix v1.1.1

Thanks.

**Comment by ChandiniGanesan** [comment]
Uncaught ReferenceError: nezasa is not defined
    at leaflet.timedimension.min.js:18
    at leaflet.timedimension.min.js:18

This is the error in my html rendered.
v1.1.0 was very useful, I really appreciate if you can fix this issue.

**Comment by bielfrontera** [comment]
Hi @ChandiniGanesan,
could you make sure that you load iso8601-js-period **before** loading timedimension? (I mean that the script tag of iso8601-js-period (nezasa) has to appear before the script tag of Leaflet.TimeDimension).
