### ISSUE TITLE
Time Dimension Images

### ISSUE THREAD

**Issue by WxmanJ** [socib/Leaflet.TimeDimension#186]
This may be more of a mapserver question, but I am trying to figure out how to setup the png images for the time dimension with wms.

Right now I have a single png setup in the .map file and it calls it just fine through leaflet, I just don’t understand how to work with multiple pngs. Does each have a unique file name that includes the time dimension in the file name?

Thank you for any assistance on this.

**Comment by bielfrontera** [comment]
Hi @WxmanJ, 
I've read the documentation of Mapserver about enabling time requests (https://www.mapserver.org/ogc/wms_time.html). It seems that it works with layers from shapefile or PostGIS with a column for the time index. But it doesn't explain how to configure if the source is a raster image. 

You could create a new layer for each time (with the time expressed in the name of the layer). And then, you can extend Timedimension to adapt to the format of the url of each layer (example: http://apps.socib.es/Leaflet.TimeDimension/examples/example16.html)
