### ISSUE TITLE
add timedimension

### ISSUE THREAD

**Issue by MannusEtten** [socib/Leaflet.TimeDimension#2]
i have several issues with the plugin

1) i do have a wms service with time dimension enabled, but the control shows "no time available"

2) when i set some options i got javascript-error
"ReferenceError: nezasa is not defined
	

if (nezasa === undefined) {"

my javascript code:

        var mapOptions = {
            center: L.latLng(52.022501, 4.438992),
            zoom: 12,
            timeDimension: true,
            timeDimensionControl: true,
            timeDimensionOptions: {
                timeInterval: "2015-04-29/2015-05-01"
                }
        };
    var map = L.map('map', mapOptions);

    var tileLayer = L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
        attribution: '© OpenStreetMap contributors'
    }).addTo(map);

    var mywms = L.tileLayer.wms("http://localhost:8080/geoserver/Mannus/wms", {
        layers: 'Mannus:meetdata',
        format: 'image/png',
        transparent: true
    });
    map.addLayer(mywms);

    var testTimeLayer = L.timeDimension.layer.wms(mywms);
    testTimeLayer.addTo(map);

**Comment by bielfrontera** [comment]
Hi @MannusEtten ,
have you included [iso8601-js-period](https://github.com/nezasa/iso8601-js-period) in your page?

The plugin needs this library to generate the list of available times from a the timeinterval that you have configured. Check out the list of javascripts included within the examples (see [example1](https://github.com/socib/Leaflet.TimeDimension/blob/master/examples/example1.html#L46)).

You might want to get the available times from the layer. The plugin can query the WMS server to get them (via GetCapabilities). To activate this, you have to include the updateTimeDimension on the timedimension layer (see [this example](https://github.com/socib/Leaflet.TimeDimension/blob/master/examples/example1.html#L46)).

Ah! There is no need to add the tileLayer to the map. It is added with the timeDimension layer.

**Comment by MannusEtten** [comment]
I added this javascript-library, so no javascript-errors at all anymore but still no option to browse through the time :-(

**Comment by bielfrontera** [comment]
Have you removed the line map.addLayer(mywms)? The layer has to be added to the map through the timedimensionLayer.

Can you add a console.log(map.getAvailableTimes()) at the bottom, and check that you have an array with three times? 

And check the network panel of your browser. You should see the requests to the WMS with the time parameter.

**Comment by MannusEtten** [comment]
i removed the line, but now firebug tells me that the function getAvailableTimes is "not a function"

so maybe i missed a script, i dont know. Shall i add my total project as zip-file for analysis?

**Comment by MannusEtten** [comment]
i got it finally working by removing the line "updateTimeDimension: true"

**Comment by bielfrontera** [comment]
Ok, perfect!

If you active this option in a wms layer, the library will get the list of available times of this layer doing a request to the getCapabilities method of the map server. In your case, it might be not necessary, and your server was probably not returning what expected.

**Comment by MannusEtten** [comment]
it does, in the getcapabilities i see the list of available times, so i think there is maybe something wrong, i dont know
