### ISSUE TITLE
iso8601-js-period cdn gives 404

### ISSUE THREAD

**Issue by nicokant** [socib/Leaflet.TimeDimension#224]
iso8601-js-period cdn dependency gives 404
https://cdn.jsdelivr.net/gh/nezasa/iso8601-js-period

**Comment by bielfrontera** [comment]
Hi @nicokant!
Thanks! I've seen that the repository has been moved to https://github.com/mdartic/iso8601-js-period

But the url that we are using on the examples (https://cdn.jsdelivr.net/npm/iso8601-js-period@0.2.1/iso8601.min.js) is working.
I will update the documentation!

**Comment by NielsHolt** [comment]
Hi
Could you also change the url to iso8601-js-period in bower.json?
And perhaps change the leaflet-version:
```
 "dependencies": {
    "iso8601-js-period": "mdartic/iso8601-js-period#latest",
    "leaflet": "latest"
  }

```
Thanks :-)
