### ISSUE TITLE
 The timedimension does not work when I am at zoom 4, but it works at smaller zooms starting at 5

### ISSUE THREAD

**Issue by guimouraO1** [socib/Leaflet.TimeDimension#230]
I have a problem that I can't solve, my map with timedimension works correctly, but from zoom 4 down it no longer works. 
You can see this on the page https://plataforma.labsat.cpa.unicamp.br/

**Comment by r1m** [comment]
What's the issue ? It looks good to me.

**Comment by guimouraO1** [comment]
> What's the issue ? It looks good to me.

I'm sorry, I managed to fix it. All you had to do was put minNativeZoom and minNativeZoom in the tileLayer.

Thanks
