### ISSUE TITLE
Player buffer usage is odd

### ISSUE THREAD

**Issue by ram-one** [socib/Leaflet.TimeDimension#26]
What's the intended behavior for the buffer ?
It's seems like the player wait until the buffer is filled then start playing and load the next time.
But it waits until the next time is loaded (buffer filled again). So we have 4 layers preloaded but never used because we always wait for 5.

Am I missing something ?
Because I expected it to load 5, then play until the buffer is empty while preloading up to 5 layers ahead of current time.

**Comment by ram-one** [comment]
Nevermind, seems like a firefox dev tool issue.

**Comment by bielfrontera** [comment]
Ok. Btw, when the buffer is full, it plays until the buffer has at least `options.minBufferReady`layers ready (by default 1)

**Comment by ram-one** [comment]
I saw it. It works but FF with debugger tools activated seems to allow only one request at a time. Without it, buffer works as expected.
