### ISSUE TITLE
Player get stuck if jumping during animation

### ISSUE THREAD

**Issue by ram-one** [socib/Leaflet.TimeDimension#28]
If you start to play an animation then jump in the timeline while the buffer is filling, it can get stuck on waiting for the buffer to be filled.
Clicking pause/play again restarts the loading and continue.

Reproduced on [Example 1](http://apps.socib.es/Leaflet.TimeDimension/examples/example1.html)

**Comment by bielfrontera** [comment]
This change should solve the problem.

Now, the player is listening the event `timeload` to reset its internal variable `_waitingForBuffer`. Therefore, the player will call the method that fills the buffer using the new time.
