### ISSUE TITLE
updateTimeDimension 

### ISSUE THREAD

**Issue by eflowbeach** [socib/Leaflet.TimeDimension#3]
I forked your repo and tried to re-create a radar layer for the US. I ran into an issue when I added the updateTimeDimensions: true   to get realtime updates...

The error I have is in this function this._availableTimes is empty. I tried increasing the loadingTimeout, but that didn't seem to help : 
  _newTimeIndexLoaded: function() {
        if (this._loadingTimeIndex == -1) {
            return;
        }
        var time = this._availableTimes[this._loadingTimeIndex];  // <---- Time is undefined because this._availableTimes is empty [].

Not sure if you have any insight, but here is my code:
https://github.com/eflowbeach/MobileWeather/blob/master/js/mobileweather.js#L51

**Comment by bielfrontera** [comment]
Hi!
I've checked the GetCapabilities response of the WMS you are using. Layer '1' doesn't have a Extent[name="time"] element. But its parent yes (it seems to be a nested layers structure).
I've changed the code, and now it gets the available times from the layer or its parent.

Take into account that you would need to setup a proxy to make the request (example https://github.com/socib/Leaflet.TimeDimension/blob/master/examples/server/proxy.php).

I will add a page in this repository to collect Leaflet.TimeDimension examples of usage. Feel free to add your case.

**Comment by eflowbeach** [comment]
Hi again,

So, I added your changes from commit 9ad9ab7 and I added a proxy call with the proxy.php script you politely provided:

https://github.com/eflowbeach/MobileWeather/commit/36c9355458e61722519902748c4b321f998bdddb

**and I still get time=undefined here:**

 _newTimeIndexLoaded: function() {
        if (this._loadingTimeIndex == -1) {
            return;
        }
        var time = this._availableTimes[this._loadingTimeIndex]; // <----still available times is empty

Thank you for your help!

**Comment by bielfrontera** [comment]
Hi,
I have uploaded a new example with this layer (see http://apps.socib.es/Leaflet.TimeDimension/examples/example14.html ).

There is a conflict between times setted in your timeDimensionOptions and the times retrieved from getCapabilities. With this configuration, the program does an intersection of both. And this intersection is null.

If you active updateTimeDimension option, after retrieving available times from the server, the timedimension component is update according to the updateTimeDimensionMode parameter. By default this mode is 'intersect', and you might want to change it to 'replace' (see https://github.com/socib/Leaflet.TimeDimension#-options-2 ).

I would recommend to not set timeInterval and period options, as you will see in the example 14. Therefore, the available times will be the ones retrieved from the server.

**Comment by eflowbeach** [comment]
Thanks Biel! It is working now. :+1:  

So, since I removed the timeInterval and period options, is there a way to limit the amount of frames to say 1 hour worth of data (maybe the cache options do this?) ? If not, I could probably provide you with a pull request that does this. 

Btw, this is a really cool library!

**Comment by bielfrontera** [comment]
Thanks! :)

It might be useful to add maxTime and minTime optional parameters to the layer, and modify the list of times retrieved from the server (probably at ```setAvailableTimes```).

But you can filter the list with the default list of times. But this default list must match the times on the server.

NOAA's layer is composed by layers each 5 minutes. You need to make sure that you create the default list of times taking a date with minutes finishing in 0 or 5 (and 0 seconds).

```javascript
var endDate = new Date();
endDate.setUTCSeconds(0, 0);
var minutes = endDate.getUTCMinutes();
endDate.setUTCMinutes(minutes - (minutes % 5));
[...]
    timeDimensionOptions: {
        timeInterval: "PT1H/" + endDate.toISOString(),
        period: "PT5M", // or  "PT10M"...
    },
```

updateTimeDimensions option is still recommended to remove the last occurrence, if it is still not available on the server.
