### ISSUE TITLE
Hide/Show a NonTiledLayer can break buffering animation

### ISSUE THREAD

**Issue by ram-one** [socib/Leaflet.TimeDimension#30]
Reproduced on example4 with current code 9af67211d0befceb9e6a49d04ed57ffe5f0999af.

If you add a Control.Layers to this example :
```javascript
L.control.layers({}, {'test': testTimeLayer}).addTo(map);
```
Scenario :
- Set FPS to ~4,
- start animation, 
- deselect the test layer, 
- wait 5 steps,
- reselect.

 :exclamation: Buffer is stuck ```Waiting until buffer is loaded. 0 of 5 loaded```
Manually stepping forward will release the buffer.

**Comment by bielfrontera** [comment]
`_evictCachedTimes` was being called with wrong arguments order, so cache management was deleting the buffer.
Now it works for me.

**Comment by ram-one** [comment]
Thanks, sorry I swap backward/forward on this one ;-)

**Comment by ram-one** [comment]
Works for me. Could you release a new version with this correction please .

**Comment by bielfrontera** [comment]
Done! :-)
