### ISSUE TITLE
Allow subdomain dispatch on NonTiledLayer

### ISSUE THREAD

**Issue by ram-one** [socib/Leaflet.TimeDimension#35]
When loading a lot of timed layers, it can be useful to be able to dispatch browser requests on different subdomains like it's done for tiles on Tilelayers.
I don't think this should be added in this plugin code, but anyway, if someone needs it : 

 ```javascript
L.NonTiledLayer.WMS.mergeOptions({
  subdomains: 'abc'
});

L.NonTiledLayer.WMS.include({

  _originalGetTileUrl: L.NonTiledLayer.WMS.prototype.getImageUrl,

  getImageUrl: function () {
    var url = this._originalGetTileUrl.apply(this, arguments);
    return L.Util.template(url, {
      s: this._getSubdomain(this.wmsParams.time),
    });
  },

  _getSubdomain: function (time) {
    var index = 0,
      date, sub = '';

    if (time && this.options.subdomains.length > 0) {
      date = new Date(time);
      //Arbitrary algorithm to get different subdomain for different time, but should be reproductible in order to allow browser cache
      index = (this.options.layers.length + date.getMinutes() + date.getHours()) % this.options.subdomains.length;
      sub = this.options.subdomains[index];
    }
    return sub;
  }
});

L.NonTiledLayer.WMS.addInitHook(function () {
  if (typeof this.options.subdomains === 'string') {
    this.options.subdomains = this.options.subdomains.split('');
  }
});
  ```

Then declare a ```L.NonTiledLayer.WMS``` with an URL like ```http://{s}.myWMS.com/...```

**Comment by ram-one** [comment]
This is not a real issue.

**Comment by bielfrontera** [comment]
Ok. Have you asked to the maintainer of L.NonTiledLayer to add this feature?

**Comment by ram-one** [comment]
This is not really useful for a normal usage of NTL because you create one request only when the user moves.
With Time buffering you could make a lot of simultaneous requests. I choose the subdomain according to the time in order to maximise parallel loading.
