### ISSUE TITLE
Can't show Pulse icon (in example9)

### ISSUE THREAD

**Issue by tecnocoma75** [socib/Leaflet.TimeDimension#39]
Hi,

thank you and congratulations for your well done job and support.
I'd like to ask you how to change default icon with a simple pulsing icon. I've read issue before about custom marker...but wasn't helpful because..yes, i can change icon and his property without problems...but when i try to pulse icon ...tha page freeze and no icon is shown. I can't find the problem...maybe interference?
I ask to you...hope you can find a solution...!

Added L.Icon.Pulse.js e L.Icon.Pulse.css to example9.html and then changed L.icon with L.icon.pulse on example9.js...
/*
var icon = L.icon({
    iconUrl: 'img/bluedot.png',
    iconSize: [18, 18],
    color:'red',
    iconAnchor: [10, 10]
});
*/
var icon = L.icon.pulse({iconSize:[20,20],color:'red'});
var customLayer = L.geoJson(null, {
    pointToLayer: function (feature, latLng) {
        if (feature.properties.hasOwnProperty('last')) {
             //marker = new L.userMarker(location.latlng,  {pulsing:true, accuracy:100, smallIcon:true}).addTo(map);
              //marker.setLatLng(location.latlng);
                //marker.setAccuracy(location.accuracy);
                //return marker;
           //return new L.marker(latLng,{icon: pulsingIcon});
            /*
               return L.circleMarker(latLng, {
                    fillColor: 'red',
                    fillOpacity: 0.5,
                    stroke: false,
                    radius: 3
                });
            */
            return new L.Marker(latLng, {
                icon: icon
            });
        }
        return L.circleMarker(latLng);
         }
});

var gpxLayer = omnivore.gpx('data/tr.gpx', null, customLayer).on('ready', function() {
    map.fitBounds(gpxLayer.getBounds(), {
        paddingBottomRight: [40, 40]
    });
});

I tried also L.Usermarker plugin...but the problem seem no to be solved.
Thanx again...hope my problem can improve your plugin :-)
Andrea

[index.zip](https://github.com/socib/Leaflet.TimeDimension/files/120646/index.zip)

**Comment by ram-one** [comment]
Your code is incomplete. Can you write a JSBin ? https://playground-leaflet.rhcloud.com/?html,output

**Comment by tecnocoma75** [comment]
Here is my full code.
Simply added reference to pulse plugin (that is working as standalone plugin) and changed reference to icon in js file.
[Leaflet_1.zip](https://github.com/socib/Leaflet.TimeDimension/files/122235/Leaflet_1.zip)

**Comment by bielfrontera** [comment]
Hi @tecnocoma75,
put `<script type="text/javascript" src="../src/L.Icon.Pulse.js"></script>` **before** example9.js.
Then, it seems to work.

**Comment by tecnocoma75** [comment]
Thanx a lot!! I'll try!

Il 08/02/2016 23:27, Biel Frontera ha scritto:
