### ISSUE TITLE
Map center following moving marker

### ISSUE THREAD

**Issue by tecnocoma75** [socib/Leaflet.TimeDimension#40]
It would be great, on the gpx/kml esample, to let user choose between "general view" of the path (map is zoomd to see the whole path, as is now), or "detail view" (where map zoom and autocenter on actual marker, and follow it while it's moving with map.panto function).
I tried to do something for the "following" option adding to the .js file:

var vInterval = setInterval(function(){
            map.panTo(marker.getLatLng()); // pan the map to follow the marker
        }, 100);
but it's not perfect...(maybe the map move faster than the  interval time)?
Besides, how can put an option, or better an icon switch for this choice, inside the map (something like the icon used for fullscreen switch)?
Thanx a lot

**Comment by ram-one** [comment]
You can listen to ```timeload``` event on timedimension.
```
timeDimesion.on('timeload', function(){ //triggered when a new time is displayed
  map.panTo(marker.getLatLng()); // pan the map to follow the marker
});
```
As for creating a control for that, check the [leaflet doc](http://mourner.github.io/Leaflet/reference.html#control)
