### ISSUE TITLE
overlay animated path+points layer

### ISSUE THREAD

**Issue by tecnocoma75** [socib/Leaflet.TimeDimension#45]
Hi
would it be possible to make example9 work with a GEOjson file?
This is because usually, other than the animated path (polyline, loaded from gpx or kml), it would be useful to show a overlay layer with the single points (each one with popup enabled to show date,location and fix number)...and it seems possible only with geoJson (or not?). I'm thinking to convert my gpx file in a geoJson (like attached, adding datetime values..) and then use:

_**var jsonLayer = L.geoJson(null, {
     onEachFeature: function (feature, layer) {layer.bindPopup(feature.properties.Luogo);}
    });
$.getJSON("data/tr.geojson", function(json) {
  jsonLayer.addData(json);
});**_
..
and then 

_**var overlayMaps = {
    "GPX Layer": gpxTimeLayer,
    "pt": jsonLayer
};**_

...but then i'll have 2 similar file with coords in my projects...and is not a good solution. All gps data should be in a single file, that serve both animated path overlay and single points layer (usr can choose if enable both or each one)
Another solution would be to find a way to extract single points from the gpx file you use and base my extra overlay layer on this...but is it possible?
[tr.zip](https://github.com/socib/Leaflet.TimeDimension/files/129841/tr.zip)

**Comment by bielfrontera** [comment]
Hi @tecnocoma75 ,
of course you can work with geojson files. You do not need to start from a gpx or kml files (converted to leaflet layers through omnivore).

You can check examples 15 and 8 (but 8 its too complex).

That geojson layers can be regular o _timedimensioned_ (created with `L.timeDimension.layer.geoJson(geoJsonLayer)`).  With this second option, note that L.TimeDimension will modify your geoJson layer according to the time. Please, read https://github.com/socib/Leaflet.TimeDimension#ltimedimensionlayergeojson

In some cases, default behaviour of L.TimeDimension with geojson layers is not what we need. In example 15, it is overwritten to do not modify features. Only show or hide them.

**Comment by tecnocoma75** [comment]
Hi,
if i create a json file with unix datetime, everything goes well...but if i use a UTC datetime (like 2015-12-29T22:30:00Z ) the script seems to stop working. It's normal?

**Comment by bielfrontera** [comment]
It accepts both timestamps and string datetimes. It should work.
Please, check the console to find any error message.
Or debug the variable `times` [here](https://github.com/socib/Leaflet.TimeDimension/blob/master/src/leaflet.timedimension.layer.geojson.js#L110)

**Comment by tecnocoma75** [comment]
I mananaged to almost do what i was searching for, thanx to your advice.
I modified ex 9 and ex 15, having coord and times load from external geojson file (with time added). 
But my solution is not perfect...timedimension generates an error and overlays doesn't compare on the map---the is an error on leaflet (but why?), even it path is created from geojson . Can you help me please?
Another question: is it possible to launch (and make it work) the html directly from a pc, without having it to load on a webserver (now i use a  xampp distribution, but i would like to distribute the project as a standalone ...but i seems that if i run i from my browser(double click on example9.html...for exmple) and not from local webserver (http://localhost:81/...), it doen's work.
Thanx again,
Andrea
[ex9.zip](https://github.com/socib/Leaflet.TimeDimension/files/149397/ex9.zip)

**Comment by bielfrontera** [comment]
Hi,
you are adding layers to the map when they are not already created. Keep in mind that $.getJSON is asynchronous, the function inside is executed when data arrives. But the next javascript instructions are executed immediately.

And you can not load data if you run the html directly, as a local file. Security reasons of the browser.
You can run a webserver in that folder easily with python:
`python -m SimpleHTTPServer` 

If you have further questions, can you create a jsfiddle with the problem? You can fork this: http://jsfiddle.net/bielfrontera/5afucs89/

**Comment by tecnocoma75** [comment]
Good, as you stated, i managed to solve the problem by using Ajax async..now the geojson loads!
But there 2 problems with animation:
1) i noticed that the effect was different from that of ex.9 with GPX, where the animation draw a line while moving while now i just have point moving without leaving a trace on the map. This is not good for my tracking project..how cani make geojson animation behave like in example9 (GPX/KML)?
2) i'd like to have an animated icon on the current position (a pulsing icon). With example9 GPX, no problem...my customized icon works thanx to pointToLayer function
`pointToLayer: function (feature, latLng) {
                        if (feature.properties.hasOwnProperty('last')) {
                            return new L.Marker(latLng, {
                                    icon: icon
                                });
                        }
                        return L.circleMarker(latLng);
                    }`
but now it seems that the 'last' point doesn't fire anymore...and circlemarker is used (ok i can replace circlemarker with ICON...and it works...but i'd like to undestand why). AddLastPoint=true is used to mark last point and make it can hake a custom icon, right?
3) can i use a custom icon for Jsonlayer (layer with point, not with the path) and another one (ex. a flashing icon) for the moving icon along the path "jsonlayerTimeLayer" (that inherits properties and icon from jsonlayer)? Maybe using the addlastpoint option? Or something else...i'd like to avoid loading twice the same json, in order to have 2 customized icon...
[http://jsfiddle.net/5afucs89/15/](url)

**Comment by tecnocoma75** [comment]
Hi,

have you got an answer for my previous question? Really thanx a lot

**Comment by ram-one** [comment]
Your data does not represent a line (Polyline). It's just a collection of point, so you have the correct behavior.
You copied the entire Cdrift example, I think you may not need the redefinition of ```_getFeatureBetweenDates```.


If you want to keep older point, change ```duration``` option or override ```_getFeatureBetweenDates``` with your own implementation

**Comment by ram-one** [comment]
Your code simplified and almost working: https://jsfiddle.net/5afucs89/17/

**Comment by steven224** [comment]
Hi, @tecnocoma75 @bielfrontera @r1m 
I am trying to do the same thing~ currently I am stuck at load my external geojson data file into script as a layer.

$.getJSON('../myfile.geojson', function(data) {
        jsonLayer = L.geoJson(data);
        jsonLayerTimeLayer = L.timeDimension.layer.trail(jsonLayer, {
  updateTimeDimension: true,
  updateTimeDimensionMode: 'replace',
  addlastPoint: true
});
jsonLayerTimeLayer.addTo(map);
map.fitBounds(jsonLayer.getBounds());
    });

this not working...console.log did not show data what I expected...
