### ISSUE TITLE
Backward playing

### ISSUE THREAD

**Issue by tomaspetterssonsmhi** [socib/Leaflet.TimeDimension#46]
Is it possible to make the L.TimeDimension.Player to buffer also for backward playing? I sometimes need to play times backward.

**Comment by bielfrontera** [comment]
It almost work! You can set `timeSteps` option to `-1`. The player will go backwards with buffering. 
But I've detected at least one problem. The player continues forever when it reaches 0. So, we should add another control to detect if animation has finished depending on timeSteps value ([here](https://github.com/socib/Leaflet.TimeDimension/blob/master/src/leaflet.timedimension.player.js#L33))

**Comment by tomaspetterssonsmhi** [comment]
I made some modifications to the code which seems to be working. 

I changed some of L_TimeDimension.Player _tick function to

    _tick: function () {
		var maxIndex =
			Math.min(this._timeDimension.getAvailableTimes().length - 1,
					this._timeDimension.getUpperLimitIndex() || Infinity);
		var maxForward = (this._timeDimension.getCurrentTimeIndex() >= maxIndex) && (this._steps > 0);
		var maxBackward = (this._timeDimension.getCurrentTimeIndex() == 0) && (this._steps < 0);
		if (maxForward || maxBackward) {
			// we reached the last step
			if (!this._loop) {
				this.pause();
				this.stop();
				this.fire('animationfinished');
				return;
			}
		}

        if (this._paused) {
            return;
        }
        var numberNextTimesReady = 0,
            buffer = this._bufferSize;

        if (this._minBufferReady > 0) {
            numberNextTimesReady = this._timeDimension.getNumberNextTimesReady(this._steps, buffer, this._loop);
            // If the player was waiting, check if all times are loaded
            if (this._waitingForBuffer) {
                if (numberNextTimesReady < buffer) {
                    console.log('Waiting until buffer is loaded. ' + numberNextTimesReady + ' of ' + buffer + ' loaded');
                    this.fire('waiting', {
                        buffer: buffer,
                        available: numberNextTimesReady
                    });
                    return;
                } else {
                    // all times loaded
                    console.log('Buffer is fully loaded!');
                    this.fire('running');
                    this._waitingForBuffer = false;
                }
            } else {
                // check if player has to stop to wait and force to full all the buffer
                if (numberNextTimesReady < this._minBufferReady) {
                    console.log('Force wait for load buffer. ' + numberNextTimesReady + ' of ' + buffer + ' loaded');
                    this._waitingForBuffer = true;
                    this._timeDimension.prepareNextTimes(this._steps, buffer, this._loop);
                    this.fire('waiting', {
                        buffer: buffer,
                        available: numberNextTimesReady
                    });
                    return;
                }
            }
        }
        this.pause();
        this._timeDimension.nextTime(this._steps, this._loop);
        if (buffer > 0) {
            this._timeDimension.prepareNextTimes(this._steps, buffer, this._loop);
        }
    }



and also slightly changed L.TimeDimension next time function:

    nextTime: function (numSteps, loop) {
        if (!numSteps) {
            numSteps = 1;
        }
        var newIndex = this._currentTimeIndex;
        var upperLimit = this._upperLimit || this._availableTimes.length - 1;
        if (this._loadingTimeIndex > -1) {
            newIndex = this._loadingTimeIndex;
        }
        newIndex = newIndex + numSteps;
        if (newIndex > upperLimit) {
            if (!!loop) {
                newIndex = this._lowerLimit || 0;
            } else {
                newIndex = upperLimit;
            }
        }
        if (newIndex < 0) {
        	if (loop) {
        		newIndex = upperLimit;
        	} else {
                newIndex = 0;
        	}
        }
        this.setCurrentTimeIndex(newIndex);
    },

**Comment by bielfrontera** [comment]
Thanks! I've finally added a new button to play backwards the animation. 
Internally, it will call the player with a negative step.

You can check [example 3](http://apps.socib.es/Leaflet.TimeDimension/examples/example3.html), which has enabled this new button.

**Comment by tomaspetterssonsmhi** [comment]
Perfect, looks great! Thanks a lot
