### ISSUE TITLE
Accessors + documentation

### ISSUE THREAD

**Issue by jekuno** [socib/Leaflet.TimeDimension#48]
It would be nice to extend the API documentation to explicitly point out how to access the TimeDimension object and the TimeDimension Control:

```
timeDimension        = map.timeDimension	
timeDimensionControl = map.timeDimensionControl
```

(Currently it's only documented how to attach them to `L.Map` through `timeDimension: true` and `timeDimensionControl: true`)

The same for accessing the player:
`player = timeDimensionControl._player`

Am I right that there's no public accessor for the player yet?

**Comment by ram-one** [comment]
These are just shortcuts.
If you want more control, you can instantiate it manually then pass it to others objects.
```javascript
var timeDimension = new L.TimeDimension(/* options*/);
var player = new L.TimeDimension.Player({timeDimension: timeDimension, /* player options */});
var timeDimensionControl = new L.Control.TimeDimension({player:player, timeDimension:timeDimension, /*Control options*/});
```

Layers use the timedimension provided in options or fallback to ```map.timeDimension```
so you may want to add 
```javascript
map.timeDimension = timeDimension
```
**or** use the options everywhere its needed
```javascript
var layer = new L.TimeDimension.Layer.WMS({timeDimension: timeDimension, , /*layer options*/});
```

**Comment by jekuno** [comment]
Thanks for your reply. I have one question regarding the manual instantiation:

I discovered that I can use `L.timeDimension.layer.geoJson` with the options `updateTimeDimension: true` and `updateTimeDimensionMode: 'replace'` to replace an existing TimeDimension.

Instead of this I would prefer to get the timeDimension from the geoJsonLayer. This would allow me to pass this timeDimension to `L.TimeDimension.Player` when creating the player instance. Is there a way to get the timeDimension from the geoJsonLayer?

**Comment by ram-one** [comment]
It does not 'replace' the timeDimension, it updates it.
timeDimension object is holding all possible times and handle time changes, time loading, etc.

If your player and your layer share the same timedimension object, they will be in sync.
You can't create a timedimension for each, they **need to share the same** one (map, layers, control and player).

```updateTimeDimension``` option tells the layer to update the timedimension object attached to it when it is intanciated. Times are deduced from the geojson data.

**Comment by ram-one** [comment]
```updateTimeDimensionMode``` tells how to update available times. 
It can replace available times with only the ones from the layer : ```replace``
It can add times from the layer : ```union``
It can restrict times to only the one shared with existing layers : ```intersect```
It can recompute periodic times based on options.period and extreme values: ```extremes```

**Comment by jekuno** [comment]
Ok, thanks for the clarification. This helped a lot.

I got it working by creating an empty TimeDimension first and then setting the available times by using `updateTimeDimension` with mode `replace`.

The comments in https://github.com/socib/Leaflet.TimeDimension/issues/48#issuecomment-190703524 have really been helpful. Maybe you could add this info (regarding manual instantiation) to the Readme.
