### ISSUE TITLE
Rewind on play

### ISSUE THREAD

**Issue by jekuno** [socib/Leaflet.TimeDimension#50]
When the animation finishes (and loop is disabled) the time slider stays at the end position (which is ok).
If the user then clicks the play button nothing happens.

Expected: The animation rewinds to the start and the playback restarts.

**Comment by ram-one** [comment]
This is intended. If loop is disabled, the player don't loop.

**Comment by ram-one** [comment]
As a workaround you can register for ```animationfinished``` event and rewind the timedimension.
```javascript
//code not tested
player.on('animationfinished', function(){
 timeDimension.setCurrentTime(timeDimension.getAvailableTimes()[0]);
});
```

**Comment by jekuno** [comment]
Thanks for this suggestion. This didn't fit my needs because it rewinds the current time (i.e. it hides the last step) but leaves the slider at the end position which is inconsistent. 

As a workaround now I register for the `play` event and reset the current time if `getCurrentTimeIndex` points to the last available time.

**Comment by bielfrontera** [comment]
This is strange. 
If you change currentTime, `timeload` event will be fired. The control is listening to this event, and when is fired, it updates the slider position.
