### ISSUE TITLE
Support for WMTS

### ISSUE THREAD

**Issue by tdamsma** [socib/Leaflet.TimeDimension#51]
Are there any plans to support tiled wms layers?

**Comment by ram-one** [comment]
It may work with ```L.TimeDimension.WMS```
If you use [mylen/leaflet.TileLayer.WMTS](https://github.com/mylen/leaflet.TileLayer.WMTS)

Timedimension will instantiate your layer for each time adding ```time```parameter to the original layer.

**Comment by tdamsma** [comment]
I tried using `L.tileLayer.wms` in Leaflet 0.7.7.and this just works.
