### ISSUE TITLE
Hide marker for current time

### ISSUE THREAD

**Issue by jekuno** [socib/Leaflet.TimeDimension#52]
I use the `duration` option of `L.TimeDimension.Layer.GeoJSON` with a `null` value to show all previous times. Is there an easy way to show all previous times except of the current time?

**Comment by bielfrontera** [comment]
You will have to override the method `_getFeatureBetweenDates` creating a new class. And change the behaviour to get the maximum index of the features coordinates. Try to change`if (featureTimes[i] > maxTime)` by `if (featureTimes[i] >= maxTime)`

**Comment by jekuno** [comment]
Thanks! :)
