### ISSUE TITLE
Js error in execution on google chrome

### ISSUE THREAD

**Issue by candidobugarin** [socib/Leaflet.TimeDimension#55]
Hello.

I created a script using your plugin to animate the radar images to Rio de Janeiro. When I run this script in Mozilla all goes well, but the Chrome don't understand that the dates of the images are already in UTC and decreases 3 hours date I step to him . You know a way to solve this? The link to the page : http://200.20.53.8/alertadecheias/radar_animation/

Thank you

**Comment by ram-one** [comment]
Are you modifying your script ?
I had different error each time I visited the page

Using [momentjs](http://momentjs.com/docs/#/displaying/format/)
this works
```javascript
function(url, time){
  var date = moment(time);
  return 'js/mac_s_04_'+date.format('YYYY-MM-DD-HH-mm')+'.png';
}
```

**Comment by candidobugarin** [comment]
Yes. As i dont have a MapServer, i created a script in python to download
the radar imagens and mount the JS.
I'm gonna try your solution.
Thanks

2016-03-04 16:12 GMT-03:00 Ram <notifications@github.com>:
