### ISSUE TITLE
Layers with different timeDimensionOptions

### ISSUE THREAD

**Issue by ClaudioCas** [socib/Leaflet.TimeDimension#6]
Dear all,
is there a way to handle layers with different options like timeInterval and period?
I would like to show only a layer at the time and switch beetween the availables (that have different time interval) without reload my page. Can I use the 'overlayadd' and 'overlayremove' event of the map and set the new time dimension options?
thanks a lot
Claudio

**Comment by bielfrontera** [comment]
9You can use the options `updateTimeDimension` and `updateTimeDimensionMode` in the definition of the layer.  

When a layer is added to the map, the plugin calls the method `setAvailableTimes` of the timedimension component if the option is `True`. The layer takes the list of times from a getCapabilities request (WMS layers) or times attributes (GeoJSON layers). And you can use the mode option to choose the operation between old available times and the new list (intersect, union, replace, extremes).

If you want to generate a custom list of times, you can create a new class that extends an existing timedimension layer and overwrite the function where the list of available times is generated.

In the [example 9](http://apps.socib.es/Leaflet.TimeDimension/examples/example9.html) you will notice that if you activate the second layer, the time control changes its extremes. I have some other implementations, but there are in our future new website.
