### ISSUE TITLE
Software to mount images

### ISSUE THREAD

**Issue by candidobugarin** [socib/Leaflet.TimeDimension#62]
Hello.
My question is not about the plugin, but I would like to know what software you use to create images with the data models. I know the Grads , but his images seem to be much better than it generates.

If you can help , I am grateful .

**Comment by bielfrontera** [comment]
Hi @candidobugarin,
images in examples 1, 3 or 6 (among others) are created by ncWMS, a software which is integrated with the THREDDS Data Server.

Check out our THREDDS installation at SOCIB: http://thredds.socib.es/thredds/catalog.html

**Comment by candidobugarin** [comment]
Thanks for the info. I will think of how to extract the png. As I have no
server needed something like the Grads , where I could insert the data
model and he returned me just the figures. With the figures I would
generate animations .

2016-04-20 16:13 GMT-03:00 Biel Frontera <notifications@github.com>:
