### ISSUE TITLE
Allow dragging the slider to instantly updating the map

### ISSUE THREAD

**Issue by trillerpfeife** [socib/Leaflet.TimeDimension#63]
I wonder if its possible to implement a function to drag the slider which instantly updated the map?!
Is this possible?
Have a nice Day

**Comment by bielfrontera** [comment]
hi @trillerpfeife,
I've just added the option `timeSliderDragUpdate` to the control to allow this behaviour. You can see this in action at [example 9](http://apps.socib.es/Leaflet.TimeDimension/examples/example9.html)

Nevertheless, I would not recommend update the map when dragging, as you might be doing too many unnecessary requests to the server. But there are some scenarios where this option can be useful.

**Comment by trillerpfeife** [comment]
Thanks @bielfrontera for your quick reply. Concerning the requests issue i thought about increasing the `map.timeDimensionControl.options.playerOptions.buffer` or better the `cache` (cacheBackward...) ?!
