### ISSUE TITLE
Extending not replacing the _update method

### ISSUE THREAD

**Issue by trillerpfeife** [socib/Leaflet.TimeDimension#65]
Hey,
I've got another question regarding your plugin. I would like to extend the `L.Control.TimeDimension._update` method, without touching your library. I thought about doing it like this:
https://gist.github.com/trillerpfeife/f1c29c8c958b6be221289c6c069d7796
but this way is somehow not working.
Do you have any idea?

Have a nice day :sunny:,
trillerpfeife

**Comment by sylram** [comment]
Use the leaflet extend method.
```
var MyTimeDimension = L.Control.Timedimension.extend({
 _update:function(){...}
});
```
Then use it as described in this comment : https://github.com/socib/Leaflet.TimeDimension/issues/48#issuecomment-190703524
Do not use the shortcut options : they will instantiate a generic control, not yours.

**Comment by trillerpfeife** [comment]
@sylram  thanks for your reply.
i thought about the same way, but:

**Comment by sylram** [comment]
Because you are affecting it back to ```L.Control.TimeDimension```. Use another variable.
```javascript
var MyCustomControl = L.Control.TimeDimension.extend(/* ...*/);
var control = new MyCustomControl(/**options**/).addTo(map);
```

**Comment by trillerpfeife** [comment]
ok thanks @sylram

**Comment by trillerpfeife** [comment]
sorry for reopening the issue :)
now i implemented it as u recommended but now i got two timesliders in the map :/
any ideas how to fix this ?

**Comment by sylram** [comment]
remove timeDimensionControl and timeDimensionControlOptions from your map options.
Like I said, they will implicitly instantiate a control. See my comment on #48

**Comment by trillerpfeife** [comment]
thanks  for your time @sylram, i will try this out

**Comment by trillerpfeife** [comment]
yeah,
i found a way to extend the `_update` method, i've done it this way:

```javascript
L.Control.TimeDimension = L.Control.TimeDimension.extend({
  _oldupdate: L.Control.TimeDimension.prototype._update,
  _update: function() {
    this._oldupdate.apply(this);

   console.log("extend _update");

  }
});
```
this way, you can modify the method without creating a new class/variable!

**Comment by sylram** [comment]
If this is all you want, you could simply modify the Control prototype.
```javascript
var _oldupdate= L.Control.TimeDimension.prototype._update;
L.Control.TimeDimension.prototype._update = function(){
 _oldUpdate.apply(this);
//do something
};
```
Your extend method will do exactly the same. I just wanted to point out that it is not related to Leaflet.

**Comment by trillerpfeife** [comment]
@sylram thanks for your support!
