### ISSUE TITLE
About example 9

### ISSUE THREAD

**Issue by xhx509** [socib/Leaflet.TimeDimension#66]
Hi
Your Leaflet applications are wonderful! I am a beginner of leaflet and  interested in your leaflet example 9 .  I tried to open  'example9.html' after your entire folder was downloaded(I didn't change anything) . However , there's no track shows on the map. Time slider shows 'Time not available' . Please see the attached file below:

![screenshot from 2016-06-20 12 16 56](https://cloud.githubusercontent.com/assets/3009401/16201799/f705fe0a-36e0-11e6-8a50-d7be333eaf35.png)

I really want to play with this example.  Could you tell me how to figure that issue? 

Thanks a lot.

Xavier

**Comment by bielfrontera** [comment]
hi Xavier,
some requests don't work if you open the html locally (as file://).

You can run a web server on Leaflet.TimeDimension-master folder. Run:
`python -m SimpleHTTPServer 8000`

And then browse to http://localhost:8000/examples/example9.html

**Comment by trillerpfeife** [comment]
@ Xavier 
for trying out stuff offline i just used the firefox not chromium. its working quite well

**Comment by xhx509** [comment]
Hi Triller and Biel:

I followed what you had mentioned. 

It works well !  That's awesome !

Thank you for your help!

Xavier
