### ISSUE TITLE
AutoPlay

### ISSUE THREAD

**Issue by candidobugarin** [socib/Leaflet.TimeDimension#67]
Hello
Not long ago, I try to run my animation with autoplay . But it did not work. I looked in the examples of you and saw that there also is not working.
You have disabled this function ?
The link of my application is : http://200.20.53.8/alertadecheias/radar_animation/index.html

Thank you very much.

**Comment by bielfrontera** [comment]
Hi @candidobugarin ,
fixed! Thanks for reporting.
