### ISSUE TITLE
Errors occur when using Leaflet 1.0.0-rc2

### ISSUE THREAD

**Issue by jbowen014** [socib/Leaflet.TimeDimension#73]
Several errors appear in the console window when using Leaflet version 1.0.0-rc2. See screenshot below.

![leaflet_errors](https://cloud.githubusercontent.com/assets/8645154/17058370/1390eaf0-4fee-11e6-824d-045638c184c8.PNG)

**Comment by bielfrontera** [comment]
Hi @jbowen014,
it was a problem with the version of Leaflet.NonTiledLayer. I've updated this plugin on the examples folder, and now it runs ok (See commit 79d9df3)
