### ISSUE TITLE
KML and GPX Animation Colors

### ISSUE THREAD

**Issue by schall11** [socib/Leaflet.TimeDimension#76]
Is there a way to change the color of the lines on the GPX and KML animation? I have a GPX file with 4 different paths that I want to symbolize differently. Can you point me in the right direction to do this?

**Comment by bielfrontera** [comment]
Hi @schall11.

Yes, you can change the path color of a geoJson layer as is described in leaflet.js documentation (see http://leafletjs.com/reference.html#geojson). If you are following example 9, you can add a style option to the customLayer which is used as base to create the geoJson layer.

Check how many features do you have: 4 LineStrings or just 1 MultiLineString. In the first case, it is easy to assign a different color to each feature. In the second case, you would need to create a new geoJson spliting the MultiLineString in LineString features.
