### ISSUE TITLE
Need some help getting started please

### ISSUE THREAD

**Issue by JRosh33** [socib/Leaflet.TimeDimension#78]
Hello,

I think this TimeDimension plugin is pretty neat. However I 'm struggling with getting started with this thing. 

Are there any write-ups on what a basic script in its entirety should look like? Things like what I need in my head section. I simply want to display a feature layer that changes location at different points in time.

I appreciate any help you willing to give.

Thanks!

**Comment by trillerpfeife** [comment]
Hey @JRosh33 ,
checkout the Leaflet TimeDimension Demos http://apps.socib.es/Leaflet.TimeDimension/examples/

**Comment by JRosh33** [comment]
Hi @trillerpfeife , I'm aware of those demos and attempted to copy and paste their code into an html file and  modify it. However, I can't even get the map div to pop up when I open it in either chrome or firefox. I'm honestly looking for just the most bare-bones example someone can give me.

**Comment by trillerpfeife** [comment]
@JRosh33 did you clone the examples folder?

**Comment by JRosh33** [comment]
Well cloning it did the trick. This is a good starting point. Thanks @trillerpfeife

**Comment by JRosh33** [comment]
Any idea how to prep data in a feature layer on a WMS? For example how do I specify my time attribute?
