### ISSUE TITLE
Is there functionality which can show timescale in this plagin?

### ISSUE THREAD

**Issue by antony-develop** [socib/Leaflet.TimeDimension#80]
![screen shot 2016-10-17 at 18 56 39](https://cloud.githubusercontent.com/assets/19634898/19431390/9afba0b0-949b-11e6-9199-4e17b7896888.png)
I'm trying to create a timescale. But I can't figure out where to start.
Is it possible to do with existing functionality? If not, can you give me a hint where to start?

**Comment by bielfrontera** [comment]
Hi @antony-develop,
it would be very interesting to develop a control like this, to have some alternatives to replace the default one.

You could start extending the class `L.Control.TimeDimension`, and change the method `_createSliderTime`. 

Your new slider (or timescale) has to implement some methods like `setValue(timeIndex)`  (move the slider to a position) and call timedimension to change the time when the slider changes (see `_sliderTimeValueChanged`).

Do you know how to create the timeslider?
You might use libraries as [timeline](http://visjs.org/docs/timeline/)
