### ISSUE TITLE
L.TimeDimension and geojson layer from proj4leaflet

### ISSUE THREAD

**Issue by supernul** [socib/Leaflet.TimeDimension#84]
Hello,

I try to display a layer created by L.Proj.geoJson() from proj4leaflet. Without L.TimeDimension.Layer(), the layer is well displayed but I can't see it with L.TimeDimension.Layer().

I don't see where is my error.

Here my project folder : 
[page_test_06.zip](https://github.com/socib/Leaflet.TimeDimension/files/573850/page_test_06.zip)

Here an extract of ma initial data : 
> <script language="javascript">
	var data={
		"crs":{"type":"name","properties":{"name":"EPSG:2154"}},
		"type":"FeatureCollection",
		"features":[
			{"type":"Feature",
			"geometry":{
				"type":"Polygon",
				"coordinates":[[[653006.945799,6862173.508896],[653003.318699,6862168.487896],[652989.237299,6862179.850096],[652993.347699,6862184.215196],[653006.945799,6862173.508896]]]
			},
			"properties":{
				"solar":3.180000,
				"time": "2012-10-27T18:02:01-06:00"}
			},
		]
	}

Here my script to create my map :
> <script language="javascript">
	function init() {
		//dÃ©finition de la projection L93
		proj4.defs("EPSG:2154", "+proj=lcc +lat_1=49 +lat_2=44 +lat_0=46.5 +lon_0=3 +x_0=700000 +y_0=6600000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs");

		
		//construction de la carte
		//var map = L.map('map', {crs: crs, scale: scale});
		var map = new L.map('map', {
			timeDimension: true,
			timeDimensionControl: true
		})

		//reprojection de la donnée
		var data2 = new L.Proj.geoJson(data, {style: doStyledata0, smoothFactor: 0});
		var data3 = new L.TimeDimension.Layer(data2);
		//définition de la bound box Ã  partir de la donnée
		//map.fitBounds(data2.getBounds());
		map.setView(data2.getBounds().getCenter(), 17);
		//ajout des données à la carte
		if (navigator.onLine) {L.tileLayer.provider('Esri').addTo(map);}
		data3.addTo(map);
	}

Thank you by advance for your help.

**Comment by bielfrontera** [comment]
Hi @supernul,
Check your geojson (file data.js). Time information is outside the properties object of the features.
You also have to load iso8601.js.

L.timeDimension.layer is an abstract class, it shouldn't be instantiated. You will have to use an extension of L.timeDimension.layer.geoJson, as in [example 15](http://apps.socib.es/Leaflet.TimeDimension/examples/example15.html), because you want to show/hide features according to the time, and the original version creates new features from linestrings.

**Comment by supernul** [comment]
Thank you for the quick answer.

I found the solution : 

>var dataLayer = new L.Proj.geoJson(data, {smoothFactor: 0});
>var dataJson = dataLayer.toGeoJSON();
>var dataLayer2 = new L.geoJSON(dataJson, {style: style});
>var dataTime = new L.TimeDimension.Layer.GeoJson(dataLayer2, {updateTimeDimension: true,,duration:"P1D"});
>dataTime.addTo(map);

And I add all necessary libraries.

To help beginners who use Leaflet instead of OL for its simplicity, simpliest examples could be helpfull.

Thank you again.
