### ISSUE TITLE
Is jQuery really useful ?

### ISSUE THREAD

**Issue by mdartic** [socib/Leaflet.TimeDimension#86]
Hello,

Thank you for your plugin, it's really helpful.

By the way, I read your code, and I'm asking myself if jQuery is really useful ?

I've detected several times jQuery :

https://github.com/socib/Leaflet.TimeDimension/blob/master/dist/leaflet.timedimension.src.js#L995

https://github.com/socib/Leaflet.TimeDimension/blob/master/dist/leaflet.timedimension.src.js#L998

https://github.com/socib/Leaflet.TimeDimension/blob/master/dist/leaflet.timedimension.src.js#L1026

https://github.com/socib/Leaflet.TimeDimension/blob/master/dist/leaflet.timedimension.src.js#L1029

https://github.com/socib/Leaflet.TimeDimension/blob/master/dist/leaflet.timedimension.src.js#L973

Do you think we could eliminate the use of jQuery ? And so, eliminate the dependency ?

**Comment by r1m** [comment]
It was needed when we used jquery ui to create the slider. Jquery ui was removed as we now use an ui made with leaflet only.

As I remember jquery was mainly used as an abstraction for xhr (ajax) calls.
Feel free to submit a PR 😉

**Comment by mdartic** [comment]
I think you use it also to parse xml (see lines 995 / 998 / 1026 / 1029).

And I discover you pass objects to functions, so in fact, jQuery is still used 'massively'.

I check if it's no too costly for me to implement.

Do you have any requirements for compatibility (IE 8 or others oldy browsers ?)

**Comment by mdartic** [comment]
I've started a PR, please review it and tell me what you think about.

**Comment by murb** [comment]
This issue can now be closed as well :)

**Comment by mdartic** [comment]
That's right :-)
