### ISSUE TITLE
Control layer output map

### ISSUE THREAD

**Issue by darkat** [socib/Leaflet.TimeDimension#9]
Hi,
The plugin works with L.control.layers. Is it possible to work from outside the map without L.control.layers (For example with buttons)?
Thanks

**Comment by bielfrontera** [comment]
Do you mean without a L.Control? Yes, it can.

First, do not add the option `timeDimensionControl` when creating the map. 
And then, you have to add your custom code manage the timedimension with your buttons. You can use methods as `previousTime` and `nextTime`, the class `L.TimeDimension.Player` and the events `timeload` and `timeloading`.

Check out the example [ImageOverlay and custom control](http://apps.socib.es/Leaflet.TimeDimension/examples/example10.html). At the bottom you will find a code that you might adapt.

**Comment by darkat** [comment]
Hi,
The methods previusTime, nextTime and L.TimeDimension.Player work well, but I have a problem with change layer wms. 
When i use addTo or onAdd, and remove or onRemove, the plugin change to current time instead of the selected time. How do I change layer?
Thanks

**Comment by bielfrontera** [comment]
Hi,
the plugin changes current time when you add a WMS layer in these two cases:
- the layer has the option setDefaultTime 
- current time wasn't already initialized.

Can you create a fiddle to show your problem?
You can fork this: http://jsfiddle.net/bielfrontera/ecu0hx7z/

**Comment by darkat** [comment]
I need the proxy.php. The code need the file proxy.php
<html>
    <head>
        <title>Leaflet TimeDimension</title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        <link rel="stylesheet" href="http://apps.socib.es/Leaflet.TimeDimension/examples/js/vendors/leaflet-0.7.3/leaflet.css" />
        <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.0/themes/smoothness/jquery-ui.css" />
        <link rel="stylesheet" href="http://apps.socib.es/Leaflet.TimeDimension/src/leaflet.timedimension.control.css" />     
    </head>
    <body>
		<div id="map" style="width: 900px; height: 400px; margin: 0 auto"></div>
		<div>
			<button onclick="map.removeLayer(saltTimeLayer); temperatureTimeLayer.addTo(map);">Temperature</button>
			<button onclick="map.removeLayer(temperatureTimeLayer); saltTimeLayer.addTo(map);">Other</button>
		</div>          
		<script type="text/javascript" src="http://apps.socib.es/Leaflet.TimeDimension/examples/js/vendors/jquery-2.0.0.min.js"></script>
        <script type="text/javascript" src="http://apps.socib.es/Leaflet.TimeDimension/examples/js/vendors/jquery-ui-1.10.2.min.js"></script>
  


        <script type="text/javascript" src="http://apps.socib.es/Leaflet.TimeDimension/examples/js/vendors/leaflet-0.7.3/leaflet.js"></script>

        <script type="text/javascript" src="http://apps.socib.es/Leaflet.TimeDimension/src/leaflet.timedimension.js"></script>
        <script type="text/javascript" src="http://apps.socib.es/Leaflet.TimeDimension/src/leaflet.timedimension.util.js"></script>
        <script type="text/javascript" src="http://apps.socib.es/Leaflet.TimeDimension/src/leaflet.timedimension.layer.js"></script>
        <script type="text/javascript" src="http://apps.socib.es/Leaflet.TimeDimension/src/leaflet.timedimension.layer.wms.js"></script>
        <script type="text/javascript" src="http://apps.socib.es/Leaflet.TimeDimension/src/leaflet.timedimension.player.js"></script>
        <script type="text/javascript" src="http://apps.socib.es/Leaflet.TimeDimension/src/leaflet.timedimension.control.js"></script>         
        <script type="text/javascript">
                var startDate = new Date();
				startDate.setUTCHours(0, 0, 0, 0);

				var map = L.map('map', {
					minZoom: 6,
					zoom: 8,
					fullscreenControl: true,
					timeDimensionControl: true,
					timeDimensionControlOptions: {
						speedSlider: false,
						position: 'bottomleft',
						playerOptions: {
							transitionTime: 2000
						}
					},
					timeDimension: true,
					center: [39.3, 2.9]
				});

				var fileNETCDF = "http://thredds.socib.es/thredds/wms/operational_models/oceanographical/hydrodynamics/model_run_aggregation/wmop/wmop_best.ncd";

				var proxy = 'server/proxy.php';


				// Temperature -----------------------------
				var temperatureLayer = L.tileLayer.wms(fileNETCDF, {
					layers: 'temp',
					format: 'image/png',
					transparent: true,    
					abovemaxcolor: "extend",
					belowmincolor: "extend",
					numcolorbands: 40,
					styles: 'boxfill/sst_36',
				});

				var temperatureTimeLayer = L.timeDimension.layer.wms(temperatureLayer, {
					proxy: proxy,
					cache: 72,
					updateTimeDimension: true,
					name: "Temperature",
					units: "K",
				});
				// ---------------------------------------------------

				// Salt ----------------------------------
				var saltLayer = L.tileLayer.wms(fileNETCDF, {
					layers: 'salt',
					format: 'image/png',
					transparent: true,    
					abovemaxcolor: "extend",
					belowmincolor: "extend",
					numcolorbands: 40,
					styles: 'boxfill/mpl_rdbu_r'
				});

				var saltTimeLayer = L.timeDimension.layer.wms(saltLayer, {
					proxy: proxy,
				});
				// ---------------------------------------------------

				temperatureTimeLayer.addTo(map);
        </script>        
    </body>
</html>

**Comment by bielfrontera** [comment]
Hi @darkat,
please, do not use the javascript files from apps.socib.es. You should download the plugin and use it from your own server.

You will probably need a proxy in your server to avoid CORS issues when retrieving GetCapabilities from the WMS server. You have an example at https://github.com/socib/Leaflet.TimeDimension/blob/master/examples/server/proxy.php
